export interface Currency {
    code: string;
    symbols: string[];
    name: string;
    exponent: number;
}

export const currencies: Currency[] = [
    { code: 'aed', symbols: ['dirham', 'د.إ', 'د.م.‏', 'د.إ.'], name: 'United Arab Emirates dirham', exponent: 2 },
    { code: 'afn', symbols: ['؋'], name: 'Afghanistan Afghani', exponent: 2 },
    { code: 'all', symbols: ['lek'], name: 'Albania Lek', exponent: 2 },
    { code: 'amd', symbols: [], name: 'Armenian Dram', exponent: 2 },
    { code: 'ang', symbols: ['ƒ'], name: 'Netherlands Antilles Guilder', exponent: 2 },
    { code: 'aoa', symbols: [], name: 'Angola Kwanza', exponent: 2 },
    { code: 'ars', symbols: ['ar$'], name: 'Argentina Peso', exponent: 2 },
    { code: 'aud', symbols: ['au$', 'a$'], name: 'Australia Dollar', exponent: 2 },
    { code: 'awg', symbols: ['ƒ'], name: 'Aruba Guilder', exponent: 2 },
    { code: 'azn', symbols: ['ман'], name: 'Azerbaijan New Manat', exponent: 2 },
    { code: 'bam', symbols: ['km'], name: 'Bosnia and Herzegovina Convertible Marka', exponent: 2 },
    { code: 'bbd', symbols: ['bb$'], name: 'Barbados Dollar', exponent: 2 },
    { code: 'bdt', symbols: [], name: 'Bangladesh Taka', exponent: 2 },
    { code: 'bgn', symbols: ['лв', 'lv'], name: 'Bulgaria Lev', exponent: 2 },
    { code: 'bhd', symbols: [], name: 'Bahraini Dinar', exponent: 2 },
    { code: 'bif', symbols: [], name: 'Burundi Franc', exponent: 2 },
    { code: 'bmd', symbols: [], name: 'Bermuda Dollar', exponent: 2 },
    { code: 'bnd', symbols: [], name: 'Brunei Darussalam Dollar', exponent: 2 },
    { code: 'bob', symbols: ['$b'], name: 'Bolivia Bolíviano', exponent: 2 },
    { code: 'brl', symbols: ['r$'], name: 'Brazil Real', exponent: 2 },
    { code: 'bsd', symbols: ['bs$'], name: 'Bahamas Dollar', exponent: 2 },
    { code: 'btn', symbols: ['nu.'], name: 'Bhutanese Ngultrum', exponent: 2 },
    { code: 'bwp', symbols: ['p'], name: 'Botswana Pula', exponent: 2 },
    { code: 'byn', symbols: ['br'], name: 'Belarus Ruble', exponent: 2 },
    { code: 'bzd', symbols: ['bz$'], name: 'Belize Dollar', exponent: 2 },
    { code: 'cad', symbols: ['ca$'], name: 'Canada Dollar', exponent: 2 },
    { code: 'cdf', symbols: [], name: 'Congolese Franc', exponent: 2 },
    { code: 'chf', symbols: [], name: 'Switzerland Franc', exponent: 2 },
    { code: 'clp', symbols: [], name: 'Chile Peso', exponent: 2 },
    { code: 'cny', symbols: [], name: 'China Yuan Renminbi', exponent: 2 },
    { code: 'cop', symbols: [], name: 'Colombia Peso', exponent: 2 },
    { code: 'crc', symbols: ['₡'], name: 'Costa Rica Colon', exponent: 2 },
    { code: 'cup', symbols: ['₱'], name: 'Cuba Peso', exponent: 2 },
    { code: 'czk', symbols: ['kč'], name: 'Czech Republic Koruna', exponent: 2 },
    { code: 'djf', symbols: ['fdj'], name: 'Djibouti Franc', exponent: 2 },
    { code: 'dkk', symbols: ['dkr'], name: 'Denmark Krone', exponent: 2 },
    { code: 'dop', symbols: ['rd$'], name: 'Dominican Republic Peso', exponent: 2 },
    { code: 'dzd', symbols: [], name: 'Algerian Dinar', exponent: 2 },
    { code: 'egp', symbols: ['£E', '￡E'], name: 'Egypt Pound', exponent: 2 },
    { code: 'ern', symbols: [], name: 'Nakfa', exponent: 2 },
    { code: 'etb', symbols: [], name: 'Ethiopian Birr', exponent: 2 },
    { code: 'eur', symbols: ['€'], name: 'Euro Member Countries', exponent: 2 },
    { code: 'fjd', symbols: ['fj$'], name: 'Fiji Dollar', exponent: 2 },
    { code: 'fkp', symbols: [], name: 'Falkland Islands (Malvinas) Pound', exponent: 2 },
    { code: 'gbp', symbols: ['£', '￡'], name: 'United Kingdom Pound', exponent: 2 },
    { code: 'gel', symbols: [], name: 'Georgia Lari', exponent: 2 },
    { code: 'ggp', symbols: [], name: 'Guernsey Pound', exponent: 2 },
    { code: 'ghs', symbols: ['¢'], name: 'Ghana Cedi', exponent: 2 },
    { code: 'gip', symbols: [], name: 'Gibraltar Pound', exponent: 2 },
    { code: 'gmd', symbols: [], name: 'Gambia Dalasi', exponent: 2 },
    { code: 'gnf', symbols: [], name: 'Guinea Franc', exponent: 2 },
    { code: 'gtq', symbols: ['q'], name: 'Guatemala Quetzal', exponent: 2 },
    { code: 'gyd', symbols: ['gy$'], name: 'Guyana Dollar', exponent: 2 },
    { code: 'hkd', symbols: ['hk$'], name: 'Hong Kong Dollar', exponent: 2 },
    { code: 'hnl', symbols: ['l'], name: 'Honduras Lempira', exponent: 2 },
    { code: 'hrk', symbols: ['kn'], name: 'Croatia Kuna', exponent: 2 },
    { code: 'huf', symbols: ['ft'], name: 'Hungary Forint', exponent: 2 },
    { code: 'idr', symbols: ['rp'], name: 'Indonesia Rupiah', exponent: 2 },
    { code: 'ils', symbols: ['₪'], name: 'Israel Shekel', exponent: 2 },
    { code: 'imp', symbols: [], name: 'Isle of Man Pound', exponent: 2 },
    { code: 'inr', symbols: ['rs', '₹'], name: 'India Rupee', exponent: 2 },
    { code: 'iqd', symbols: [], name: 'Iraqi Dinar', exponent: 2 },
    { code: 'irr', symbols: ['﷼'], name: 'Iran Rial', exponent: 2 },
    { code: 'isk', symbols: [], name: 'Iceland Krona', exponent: 2 },
    { code: 'jep', symbols: [], name: 'Jersey Pound', exponent: 2 },
    { code: 'jmd', symbols: ['j$'], name: 'Jamaica Dollar', exponent: 2 },
    { code: 'jod', symbols: [], name: 'Jordanian Dinar', exponent: 2 },
    { code: 'jpy', symbols: ['¥', '¥', '円'], name: 'Japan Yen', exponent: 2 },
    { code: 'kes', symbols: [], name: 'Kenyan Shilling', exponent: 2 },
    { code: 'kgs', symbols: ['лв'], name: 'Kyrgyzstan Som', exponent: 2 },
    { code: 'khr', symbols: ['៛'], name: 'Cambodia Riel', exponent: 2 },
    { code: 'kmf', symbols: [], name: 'Comoro Franc', exponent: 2 },
    { code: 'kpw', symbols: ['₩'], name: 'Korea (North) Won', exponent: 2 },
    { code: 'krw', symbols: ['₩'], name: 'Korea (South) Won', exponent: 2 },
    { code: 'kwd', symbols: [], name: 'Kuwaiti Dinar', exponent: 2 },
    { code: 'kyd', symbols: ['ky$'], name: 'Cayman Islands Dollar', exponent: 2 },
    { code: 'kzt', symbols: ['тг'], name: 'Kazakhstan Tenge', exponent: 2 },
    { code: 'lak', symbols: ['₭'], name: 'Laos Kip', exponent: 2 },
    { code: 'lbp', symbols: [], name: 'Lebanon Pound', exponent: 2 },
    { code: 'lkr', symbols: ['₨'], name: 'Sri Lanka Rupee', exponent: 2 },
    { code: 'lrd', symbols: ['lr$'], name: 'Liberia Dollar', exponent: 2 },
    { code: 'lsl', symbols: [], name: 'Lesotho Loti', exponent: 2 },
    { code: 'ltl', symbols: ['lt'], name: 'Lithuanian Litas', exponent: 2 },
    { code: 'lyd', symbols: [], name: 'Libyan Dinar', exponent: 2 },
    { code: 'mad', symbols: ['dh', 'dhs'], name: 'Moroccan Dirham', exponent: 2 },
    { code: 'mdl', symbols: [], name: 'Moldovan Leu', exponent: 2 },
    { code: 'mga', symbols: [], name: 'Malagasy Ariary', exponent: 2 },
    { code: 'mkd', symbols: ['ден'], name: 'Macedonia Denar', exponent: 2 },
    { code: 'mmk', symbols: [], name: 'Myanmar Kyat', exponent: 2 },
    { code: 'mnt', symbols: ['₮'], name: 'Mongolia Tughrik', exponent: 2 },
    { code: 'mop', symbols: [], name: 'Macao Pataca', exponent: 2 },
    { code: 'mro', symbols: [], name: 'Mauritania Ouguiya', exponent: 2 },
    { code: 'mur', symbols: ['₨'], name: 'Mauritius Rupee', exponent: 2 },
    { code: 'mvr', symbols: [], name: 'Maldives Rufiyaa', exponent: 2 },
    { code: 'mwk', symbols: [], name: 'Malawi Kwacha', exponent: 2 },
    { code: 'mxn', symbols: [], name: 'Mexico Peso', exponent: 2 },
    { code: 'myr', symbols: ['rm'], name: 'Malaysia Ringgit', exponent: 2 },
    { code: 'mzn', symbols: ['mt'], name: 'Mozambique Metical', exponent: 2 },
    { code: 'nad', symbols: ['na$'], name: 'Namibia Dollar', exponent: 2 },
    { code: 'ngn', symbols: ['₦'], name: 'Nigeria Naira', exponent: 2 },
    { code: 'nio', symbols: ['c$'], name: 'Nicaragua Cordoba', exponent: 2 },
    { code: 'nok', symbols: [], name: 'Norway Krone', exponent: 2 },
    { code: 'npr', symbols: ['₨'], name: 'Nepal Rupee', exponent: 2 },
    { code: 'nzd', symbols: ['nz$'], name: 'New Zealand Dollar', exponent: 2 },
    { code: 'omr', symbols: ['﷼'], name: 'Oman Rial', exponent: 2 },
    { code: 'pab', symbols: ['b/.'], name: 'Panama Balboa', exponent: 2 },
    { code: 'pen', symbols: ['s/.'], name: 'Peru Sol', exponent: 2 },
    { code: 'pgk', symbols: [], name: 'Papua New Guinea Kina', exponent: 2 },
    { code: 'php', symbols: ['₱'], name: 'Philippines Peso', exponent: 2 },
    { code: 'pkr', symbols: ['₨'], name: 'Pakistan Rupee', exponent: 2 },
    { code: 'pln', symbols: ['zł'], name: 'Poland Zloty', exponent: 2 },
    { code: 'pyg', symbols: ['gs'], name: 'Paraguay Guarani', exponent: 2 },
    { code: 'qar', symbols: ['﷼'], name: 'Qatar Riyal', exponent: 2 },
    { code: 'ron', symbols: ['lei'], name: 'Romania New Leu', exponent: 2 },
    { code: 'rsd', symbols: ['дин'], name: 'Serbia Dinar', exponent: 2 },
    { code: 'rub', symbols: ['₽'], name: 'Russia Ruble', exponent: 2 },
    { code: 'rwf', symbols: [], name: 'Rwanda Franc', exponent: 2 },
    { code: 'sar', symbols: ['﷼', 'ر.س.'], name: 'Saudi Arabia Riyal', exponent: 2 },
    { code: 'sbd', symbols: ['sb$'], name: 'Solomon Islands Dollar', exponent: 2 },
    { code: 'scr', symbols: ['₨'], name: 'Seychelles Rupee', exponent: 2 },
    { code: 'sdg', symbols: ['ج.س.'], name: 'Sudanese Pound', exponent: 2 },
    { code: 'sek', symbols: ['kr'], name: 'Sweden Krona', exponent: 2 },
    { code: 'sgd', symbols: ['sg$'], name: 'Singapore Dollar', exponent: 2 },
    { code: 'shp', symbols: [], name: 'Saint Helena Pound', exponent: 2 },
    { code: 'sle', symbols: ['le'], name: 'Sierra Leonean new Leone', exponent: 2 },
    { code: 'sll', symbols: [], name: 'Sierra Leone', exponent: 2 },
    { code: 'sos', symbols: ['s'], name: 'Somalia Shilling', exponent: 2 },
    { code: 'srd', symbols: ['sr$'], name: 'Suriname Dollar', exponent: 2 },
    { code: 'ssp', symbols: [], name: 'South Sudanese Pound', exponent: 2 },
    { code: 'std', symbols: [], name: 'Sao Tome and Principe Dobra', exponent: 2 },
    { code: 'svc', symbols: [], name: 'El Salvador Colon', exponent: 2 },
    { code: 'syp', symbols: [], name: 'Syria Pound', exponent: 2 },
    { code: 'szl', symbols: [], name: 'Swaziland Lilangeni', exponent: 2 },
    { code: 'thb', symbols: ['฿'], name: 'Thailand Baht', exponent: 2 },
    { code: 'tjs', symbols: [], name: 'Tajikistan Somoni', exponent: 2 },
    { code: 'tmt', symbols: [], name: 'Turkmenistan New Manat', exponent: 2 },
    { code: 'tnd', symbols: [], name: 'Tunisian Dinar', exponent: 2 },
    { code: 'try', symbols: [], name: 'Turkey Lira', exponent: 2 },
    { code: 'ttd', symbols: ['tt$'], name: 'Trinidad and Tobago Dollar', exponent: 2 },
    { code: 'tvd', symbols: ['tv$'], name: 'Tuvalu Dollar', exponent: 2 },
    { code: 'twd', symbols: ['nt$'], name: 'Taiwan New Dollar', exponent: 2 },
    { code: 'tzs', symbols: [], name: 'Tanzanian Shilling', exponent: 2 },
    { code: 'uah', symbols: ['₴'], name: 'Ukraine Hryvnia', exponent: 2 },
    { code: 'ugx', symbols: [], name: 'Uganda Shilling', exponent: 2 },
    { code: 'usd', symbols: ['$', '﹩', '＄', 'us$'], name: 'United States Dollar', exponent: 2 },
    { code: 'uyu', symbols: ['$u'], name: 'Uruguay Peso', exponent: 2 },
    { code: 'uzs', symbols: ['лв'], name: 'Uzbekistan Som', exponent: 2 },
    { code: 'vef', symbols: ['bs'], name: 'Venezuela Bolivar', exponent: 2 },
    { code: 'vnd', symbols: ['₫'], name: 'Viet Nam Dong', exponent: 2 },
    { code: 'vuv', symbols: [], name: 'Vanuatu Vatu', exponent: 2 },
    { code: 'wst', symbols: [], name: 'Samoa Tala', exponent: 2 },
    { code: 'xaf', symbols: [], name: 'Central African Franc', exponent: 2 },
    { code: 'xcd', symbols: ['xc$'], name: 'East Caribbean Dollar', exponent: 2 },
    { code: 'xof', symbols: [], name: 'West African Franc', exponent: 2 },
    { code: 'xpf', symbols: [], name: 'CFP Franc', exponent: 2 },
    { code: 'yer', symbols: ['﷼'], name: 'Yemen Rial', exponent: 2 },
    { code: 'zar', symbols: ['r'], name: 'South Africa Rand', exponent: 2 },
    { code: 'zmw', symbols: [], name: 'Zambian Kwacha', exponent: 2 },
    { code: 'zwd', symbols: ['z$'], name: 'Zimbabwe Dollar', exponent: 2 },
    { code: 'zwl', symbols: [], name: 'Zimbabwe Dollar', exponent: 2 },
];
